nodeLinker: node-modules

# Force installation in workspaces
nmHoistingLimits: workspaces

# Optional optimizations
enableGlobalCache: false
compressionLevel: mixed

# Network settings for faster installs
httpTimeout: 60000
networkConcurrency: 16